name: CI Build

on:
  push:
    branches:
      -develop 
  pull_request:
    branches:
      -develop 
      -master
jobs:
  build:
    runs-on:

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirments.txt
    - name: Run Tests
      run: |
        pytest


    
